apiVersion: operator.baaas/v1alpha1
kind: DecisionRequest
metadata:
  name: example-decision-request
spec:
  customerId: rromerom
  name: example-decision
  version: "1"
  source: 's3://baaas-storage-dev/customers/example/example-decision/1/dmn.xml'
  webhooks:
    - http://localhost:18080/callback